app = "open-match"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
cmd = ["run", "-A", "--no-check", "--unstable", "./main.js"]
auto_rollback = true

[env]
PORT = "8000"
PRIMARY_REGION = "ams"

[[services]]
protocol = "tcp"
internal_port = 8000

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"]
