// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[id].jsx";
import * as $1 from "./routes/_app.jsx";
import * as $2 from "./routes/_middleware.jsx";
import * as $3 from "./routes/api/login.js";
import * as $4 from "./routes/api/rooms.js";
import * as $5 from "./routes/api/rooms/[id].js";
import * as $6 from "./routes/index.jsx";
import * as $7 from "./routes/new.jsx";
import * as $$0 from "./islands/add-room.jsx";
import * as $$1 from "./islands/board-display.jsx";
import * as $$2 from "./islands/login-form.jsx";
import * as $$3 from "./islands/mobile-menu.jsx";
import * as $$4 from "./islands/piece-display.jsx";
import * as $$5 from "./islands/rooms-list.jsx";

const manifest = {
  routes: {
    "./routes/[id].jsx": $0,
    "./routes/_app.jsx": $1,
    "./routes/_middleware.jsx": $2,
    "./routes/api/login.js": $3,
    "./routes/api/rooms.js": $4,
    "./routes/api/rooms/[id].js": $5,
    "./routes/index.jsx": $6,
    "./routes/new.jsx": $7,
  },
  islands: {
    "./islands/add-room.jsx": $$0,
    "./islands/board-display.jsx": $$1,
    "./islands/login-form.jsx": $$2,
    "./islands/mobile-menu.jsx": $$3,
    "./islands/piece-display.jsx": $$4,
    "./islands/rooms-list.jsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
